OpenChemistry/stempy

examples/electron.ipynb
stempy/electron.cpp
stempy/electron.h

This is a simpler representation rather than have to pass around
std::pair.

Return electron count position as a 1D array index

---

examples/create_hdf5.py

This should be a variable set by the user, not hard-coded.

Fix H5 stem image reader version

---

stempy/reader.cpp

Since a reference wasn't being used, a copy was being made,
and then the copy was zeroed. This resulted in the original
image numbers being unchanged, and it resulted in completely
white bright and dark fields.

Use a reference when zeroing image numbers

---

python/stempy/__init__.py
setup.py

Otherwise, `_io` and `_image` will fail to get imported
for local development.

Import pybind11 modules in the new __init__.py

---

python/stempy/image/__init__.py
stempy/image.cpp
stempy/image.h
stempy/mask.cpp
stempy/mask.h

If the values for the centers are less than 0, they
will be automatically calculated.
Fixes: #39
For our stem image sample, the default, 288, is this:
Bright
=====
Dark
====
If we change it to 250, for example:
Bright
=====
Dark
====

Allow center of annular masks to be specified

---

stempy/reader.cpp

We end put with a vector of the wrong size, 2 instead of 1.

Remove unnecessary resize

---

examples/electron_stem_image.py
examples/stem_image.ipynb
examples/stem_image.py
python/image.cpp
python/stempy/image/__init__.py
python/stempy/io/__init__.py
stempy/image.cpp
stempy/image.h
stempy/reader.cpp

Multiple stem images can now be created in one go, which can
save a lot of time compared to doing them all individually.
A couple of python examples were modified to illustrate the new API.
But the old python API still works for backward compatibility.

Added ability to create many stem images in one go

---

python/stempy/pipeline/__init__.py

This is a possible way to declare the pipeline parameters in a way that can be sent over to the client to automatically generate the input forms.
Usage:
```python
from stempy.pipeline import pipeline, parameter
@pipeline('Annular Mask', 'Creates STEM images using annular masks')
@parameter('centerX', type='number', label='Center X', default=-1)
@parameter('centerY', type='number', label='Center Y', default=-1)
@parameter('innerRadius', type='number', label='Inner Radius', default=0)
@parameter('outerRadius', type='number', label='Outer Radius', default=0)
def execute(path=None, **params):
centerX = params.get('centerX')
centerY = params.get('centerY')
innerRadius = params.get('innerRadius')
outerRadius = params.get('outerRadius')
```
I'm open to discussion

Add decorator to declare the arguments of a pipeline

---

examples/benchmark_electron_counting.py
examples/create_hdf5.py
examples/electron.ipynb
python/image.cpp
python/stempy/image/__init__.py
stempy/electron.cpp
stempy/electron.h
stempy/image.cpp
stempy/image.h

A new struct, ElectronCountedData, was added that contains the previous
output of electronCount(), plus the scan and frame dimensions. This is
done so that the scan and frame dimensions can be obtained again later
in the code.
A new overload of createSTEMImagesSparse() was also added that takes in
an ElectronCountedData argument. This function can be called from the
python code as well.
An example of using the ElectronCountedData for creating a sparse stem
image can be seen now in `electron.ipynb`.
This fixes the third point of #76.

Return dimensions from electronCount() function

---

stempy/electronthresholds.cpp
stempy/electronthresholds.h

Allow the backgroundThresholdNSigma and xRayThresholdNSigma arguments
to be doubles instead of ints.
Fixes the first point in #76.

Allow electron threshold parameters to be doubles

---

python/image.cpp
python/stempy/image/__init__.py
stempy/electronthresholds.cpp
stempy/electronthresholds.h

The verbose option causes the electron threshold function
to print out to the console a variety of variables. These
are the current variables that are printed out:
```
numberOfSamples
min
max
mean
variance
stdDev
numberOfBins
xRayThresholdNSigma
backgroundThresholdNSigma
xrayThreshold
backgroundThreshold
```
Fixes: #76

Add verbose option to electron threshold function

---

stempy/image.cpp

When the sparse stem image functions were originally created, they
expanded the sparse data so that they could re-use functions that
are used by regular stem images. This, however, creates a very large
copy for some datasets.
This modification avoids that expansion and simplifies sparse stem
image creation. It should, in theory, be faster as well.

Do not expand sparse data for sparse stem images

---

examples/electron_mpi.py

This is an example of performing the electron counting using MPI. It seems to work, and it provides a decent speed increase as well.
One concern we had was that the background thresholds and x-ray thresholds may not be as accurate, because each MPI process can currently only sample from its own files. However, for our test dataset, it does not appear to produce a noticeable difference.
Timings are interesting. On ulex, with `OMP_NUM_THREADS=1`, vtkm with openmp, and disk caching in use, these are the timing results:
```
Num MPI Processes: Seconds
1: 66.93
2: 66.80
4: 33.42
8: 19.14
```
* Note for our example, we have 8 files. Four of the files are 2.5 GB, and four are 100 MB. The lack of improvement from one MPI process to two is because one process is reading/processing all of the large …

Add electron MPI example

---

python/io.cpp
python/pyreader.cpp
python/pyreader.h

The data was previously copied in order to prevent seg faults. These
changes fix the seg faults, though, by keeping a copy of the pybind11
object around so that internal PyObject's reference count doesn't go
to zero.
A wrapper is needed to store the pybind11 object so that the API for
calling it is similar to std::shared_ptr, so that it can be used
in the stempy C++ template functions. Additionally, the pybind11 object
is stored in a std::shared_ptr internally, so that the PyBlock object
can be copied without copying the data (as is done with other types of
Block objects in stempy).
const_cast is needed in io.cpp because the buffer_info constructor
requires a non-const pointer. pybind11 also internally uses const_cast
to achieve the same purpose.

Avoid copying data for PyReader's PyBlock

---

python/pyreader.cpp

I couldn't actually reproduce the warning for some reason, but I think this should fix it.

Fix order of initialization warning

---

docs/source/conf.py

We are doing this manually to avoid problems with nested classes.

Mock out pybind11 generate classes

---

.readthedocs.yml
docs/requirements.txt
docs/source/conf.py
docs/source/modules.rst
docs/source/stempy.image.rst
docs/source/stempy.io.rst
python/stempy/io/__init__.py

This adds a .readthedocs.yml file, and it makes some changes to
the docs code so that Read the Docs will work.
The files automatically generated by `sphinx-apidoc` were committed,
because Read the Docs does not run `sphinx-apidoc`.

Initial setup for Read the Docs

---

python/stempy/image/__init__.py
python/stempy/io/__init__.py

This adds descriptions for our named tuples in the return type
descriptions of the functions that return them.

Add descriptions for our named tuples

---

README.md

The singularity instructions link points to the Read the Docs page.

Add RTD badge and singularity instructions link

---

docker/Dockerfile

It was previously building master, and updates to master could potentially
break the Dockerfile. Lock down the version so we can get a consistent
docker image.
Fixes: #120

Lock down vtk-m version in Dockerfile to 1.5

---

stempy/electron.cpp
stempy/electronthresholds.cpp
stempy/image.cpp
stempy/mask.cpp

This fixes compiler warnings that are caused by some automatic type
conversions and comparisons between signed and unsigned integers.

Fix compiler warnings

---

examples/create_hdf5.py
python/stempy/io/__init__.py
stempy/reader.cpp

In order for a reader of the HDF5 stempy file to know the
scan positions, one of two things needs to be true:
1. The frame images need to be sorted numerically, starting with 0
2. The "scan_positions" need to be written to a data set
This fixes the "create_hdf5.py" file so that the frame images are
sorted numerically (additionally, these changes also remove the need
to have two copies of the data in memory, which was a problem with
"create_hdf5.py" before).
This PR also adds an option to write the scan positions in
stempy.io.save_raw_data(), in case that is preferable to callers.
Fixes: #111

Sort frame data when writing to an HDF5 file

---

examples/electron.ipynb
examples/electron_mpi.py
examples/electron_stem_image.py
python/image.cpp
python/stempy/image/__init__.py
setup.py
stempy/image.cpp
stempy/image.h

Rather than having separate functions for sparse STEM image creation
such as "create_stem_image_sparse", combine all of the sparse STEM
image functions (and the singular "create_stem_image" function) into
"create_stem_images".
"create_stem_images" determines the type of its input, and calls the
correct function signature based upon it. Now, a user can pass to
"create_stem_images" one of four options:
1. A stempy.io.reader
2. An open h5py file
3. ElectronCountedData (returned from electron counting) sparse data
4. A numpy array of sparse data
The "create_stem_images" function handles all of these inputs.
Additionally, on the C++ side, the "...Sparse()" functions were renamed
to overload "createSTEMImages".
This reduces the number of function names that we have to work with,
and it allows …

Overload create stem image functions

---

README.md

For the build instructions, instead of linking to the BUILDING.md
file in the GitHub repo, link to the Read the Docs page.

Use the RTD page for the building link

---

python/stempy/image/__init__.py

The previous behavior would convert tuple radii into a list
of tuples, which would cause an overload resolution error.
Pybind11 can automatically convert the tuples into std::vector,
so allow them to be passed as well.
Fixes: #136

Allow radii to be tuples in create_stem_images()

---

python/pyreader.h

Although the DataHolder class was acquiring the GIL before
decrementing the reference count on the shared pointer when "reset()"
was called, there were a few cases where the GIL was not acquired.
This causes a crash when the last shared pointer is destroyed.
The cases in DataHolder where the GIL was not acquired were:
1. Destructor
2. Copy assignment
3. Move assignment
Both 1 and 2 were being performed in the electron counting code.
This hopefully fixes all of the cases where the shared pointer's
reference count is decremented without the GIL being acquired.
Fixes: #138

Ensure GIL is acquired before deleting py::array

---

examples/create_hdf5.py
examples/electron_mpi.py
python/stempy/image/__init__.py
python/stempy/io/__init__.py

Basically, you can now read the electron counted data from an
HDF5 file and then use it to create a stem image like so:
```python
counts = io.read_electron_counts('/path/to/file.h5')
stem_img = image.create_stem_images(counts, inner_radius, outer_radius)[0]
```
You can also now create your own python class that has the attributes
`data`, `scan_dimensions`, and `frame_dimensions`, and you can pass
that into `image.create_stem_images()` to be used as electron counted data.
Fixes: #140

Read electron counted data from HDF5 file

---

python/image.cpp
python/stempy/image/__init__.py
stempy/electron.cpp
stempy/electron.h
stempy/electronthresholds.cpp
stempy/electronthresholds.h
stempy/reader.cpp
stempy/reader.h

This PR adds support for providing a gain mask that will be applied to each frame before electron counting is performed. For example:
```python
gain = np.ndarray((576,576), dtype=np.float32)
gain.fill( 0.5 )
ec = stim.electron_count(
reader, 
dark, 
number_of_samples=1200, 
verbose=True, 
threshold_num_blocks=20, 
xray_threshold_n_sigma=175, 
background_threshold_n_sigma=threshold, 
gain=gain
)
```
Not that this had been implement using templates, so the penalty of using floats only applies if a gain is provided.
I have pushed an image built from the PR for testing:
```openchemistry/stempy:gain```

Add support for providing gain mask when electron counting

---

docker/Dockerfile.ipykernel

Bump version of ipympl to be compatible with new JupyterLab deployment
at NERSC.

Bump version of ipympl

---

python/image.cpp
python/stempy/image/__init__.py
stempy/electron.cpp
stempy/electron.h
stempy/electronthresholds.cpp
stempy/electronthresholds.h
stempy/image.cpp
stempy/image.h

Instead of a 64-bit double, use 32-bit floats for the dark reference
type, since 32-bit is usually big enough.
Fixes: #156

Use 32-bit floats for dark reference type

---

python/image.cpp

This steals the data from the C++ vectors and moves it to numpy arrays.
The numpy arrays will automatically clean up the data when they are
finished.
This prevents a copy being made of the electron counted data.

Move electron data in no-copy operation to numpy

---

stempy/reader.cpp
stempy/reader.h

By holding on to the stream while processing a frame we were cause starvation of that stream. This caused the streams to be read unevenly cause the cache to grown as frames could not be reconstructed.
Fixes: #172

Release stream before processing frame

---

python/image.cpp
python/io.cpp
python/stempy/image/__init__.py
python/stempy/io/__init__.py
stempy/electron.cpp
stempy/electron.h
stempy/reader.cpp
stempy/reader.h

This readers the headers first to build up a frame map and then uses a second pass to read the data. This reduces memory usage and will provide the opportunity to parallelize across nodes.

Add multi-pass reader

---

.readthedocs.yml
docs/requirements.txt
docs/source/conf.py

It isn't really needed - we are already appending the path
to the python files to the sys.path. And we are mocking the
stempy._io and stempy._image imports already.
This also adds _threaded_multi_pass_reader to the list of _io_mock
objects to prevent an error involving multiple inheritance with
different metaclasses.
deprecation is also added as a requirement for the docs, since it
is needed to display the deprecation in the documentation.

Skip pip install stempy for read the docs

---

docker/Dockerfile
docker/Dockerfile.scipy-notebook

Previously, symlinks were being preserved when the copy occurred. The
symlinks pointed into the /home/jovyan directory.
When a singularity shell was started, the user would be "jovyan", so
there would be no issue importing the files.
However, if jupyter was started instead, the user would be the current
user on the host OS. And this user would have permissions issues with
reading into the /home/jovyan directory.
To fix this, dereference the symlinks on `cp` to avoid having symlinks
pointing into `/home/jovyan`.
This was tested and seems to have fixed the issue.

Dereference symlinks to fix singularity

---

python/stempy/io/__init__.py

This makes it more accessible...
Fixes: #211

Allow `from stempy.io import SparseArray`

---

.github/workflows/build_wheels.yml

~It's end of life is coming in \~7 weeks, and the latest cibuildwheel
no longer supports it.~
~We can go ahead and remove it, since we do not believe anyone has a
specific need for the python 3.6 wheels.~
Looks like it was actually musl wheels that were the problem. CI build wheel started supporting musl wheels since a couple of weeks ago. We don't need any immediate support for them, so I added them to the skip list, and I put python 3.6 back on.

Skip musl wheels

---

python/stempy/image/__init__.py

This fixes the issue with `stempy.image.calculate_sum_sparse()` which incorrectly calculated results for scans with multiple frames per probe position

Add extra for loop to account for multiple frames

---

examples/electron_count.py
python/image.cpp
python/stempy/image/__init__.py
python/stempy/io/sparse_array.py
stempy/electron.cpp
stempy/electron.h
tests/test_sparse_array.py

This adds metadata to the SparseArray class than will be saved/loaded
via HDF5. A basic test was also added to ensure this works.
Now, when electron counting is performed, the metadata on the sparse
array gets set to the electron counting metadata (thresholds mostly).
This way, we can also keep and save the electron counting metadata to
the HDF5 file.
Fixes: #220

Add metadata to SparseArray

---

python/stempy/image/__init__.py

These functions were flagged for deprecation starting in 1.1, which
we are now on.

Remove deprecated functions flagged for 1.1

---

python/image.cpp
python/stempy/image/__init__.py
python/stempy/io/sparse_array.py
stempy/electron.cpp
stempy/electron.h
tests/test_sparse_array.py

Previously, in the electron counting, we would combine two sparse arrays
if they had the same scan positions. Now, we are modifying this so that
the sparse arrays are kept separately per frame, and duplicates are no
longer allowed in a single sparse array.
The ElectronCountedData struct now has a scanPositions vector to indicate
which scan a sparse array belongs to, since the data vector no longer
matches the size of the scan.
This also updates the SparseArray class to perform faster (and correct)
arithmetic and expanding based upon the new way that the sparse data is
formatted.
I have tested the electron counting with a dataset that has two frames
per scan position, and for fully expanding the output sparse array, I
received the same result before and after these changes, which indicates …

Separate sparse arrays with same scan position

---

python/CMakeLists.txt
python/stempy/__init__.py
python/stempy/utils.py

This can be obtained via `stempy.__version__`.
This also modifies some cmake logic to remove the need to specify every python file and directory for installation.
Fixes: #238

Add stempy version

---

python/image.cpp
python/stempy/image/__init__.py
stempy/image.cpp
stempy/image.h

This fixes a crash that would occur if `create_stem_images()` was
called using v2 data, and there were more than one frame per scan
position.
Internally, it does so by moving around an additional array of scan
positions to keep track of which frame belongs to which scan position.
The python API remains unchanged.
Fixes: #243

Fix create_stem_images() crash with v2 data

---

docs/source/StempyH5Format.rst
h5cpp/h5readwrite.cpp
h5cpp/h5readwrite.h
python/stempy/io/__init__.py
stempy/reader.cpp

In the HDF5 format, save the scan dimensions to /frames as
a list of two attributes (width, height).
This also changes the convention we currently have to save
dimension attributes as a list of two attributes (width, height)
rather than as separate attributes, such as Nx and Ny.
This is not fully tested and may not fully work.
Fixes: #126

Save the scan dimensions to /frames

---

python/stempy/io/sparse_array.py

When large scan indices were being used for sparse slicing, these loops
were taking way too long to regenerate the indices of the scan positions.
For very large scans, it could take over a second (or even much longer)
to index into the sparse array with large scan positions.
This change results in significantly faster slicing. For one example
where it would take over 1 second to perform the sparse slicing, it
now takes 4 microseconds.
Fixes: #246.

Fix sparse slicing performance in SparseArray

---

python/image.cpp
python/stempy/image/__init__.py
python/stempy/io/compatibility.py
python/stempy/io/sparse_array.py
stempy/electron.cpp
stempy/electron.h
stempy/electron_mpi.cpp
stempy/image.cpp
stempy/image.h
tests/conftest.py
tests/test_image.py
tests/test_sparse_array.py

Version 3 of the SparseArray and electron counting methods changes the
data shape from a flat array of sparse frames to a 2D array, where the
first dimension is the scan position, and the second dimension is the
index of a frame at that scan position. This removes the need for the
`scan_positions` array (previously used to indicate which scan position
each sparse frame corresponded to).
Now, the data array passed to the SparseArray must either have a shape
of `(num_scans, frames_per_scan)` or just `(num_scans,)` (where one frame
per scan will be assumed, and the shape will be changed automatically to
`(num_scans, 1)`. Validation is performed to ensure this is the case, or
an exception will be raised.
This simplifies a lot of the logic involving multiple frames per scan
position, and …

Refactor SparseArray and methods to data version 3

---

.github/workflows/build_wheels.yml

These are not working with our current version of pybind11. Let's
skip them for now.

Skip python 3.11 wheels

---

python/stempy/io/sparse_array.py
tests/test_sparse_array.py

It would previously raise an exception, because some of the logic needs to
take into account the possibility of having multiple frames per scan.
This commit fixes the issue.
Fixes: #261

Fix binning scans with multiple frames per scan

---

python/stempy/image/__init__.py
tests/conftest.py
tests/test_image.py

The logic in `com_sparse` was not correct when `init_center` was used and `crop_to` was not used. In this case the COM was returned as the `init_center`. This fixes that problem.
`com_sparse` will also set the COM to `nan` in cases where `crop_to` leads to no counts inside the cropped area. This matches the behavior for empty frames.
I also added a `pytest` fixture to return a simulated `SparseArray` with some variable parameters such as the size and position of the disk in diffraction space. I use this to test the new logic in `com_sparse`
@psavery How would I change `simulate_sparse_array` to have multiple frames per position? Im not sure the size of the `data` input to `SparseArray`'s `kwargs`.

Fix com sparse parameters

---

python/image.cpp
python/stempy/image/__init__.py
stempy/electron.cpp
stempy/electron.h
stempy/electron_mpi.cpp
stempy/electronthresholds.cpp

This adds a row dark algorithm to the electron counting. The row dark algorithm is applied to each frame pixel like the following:
```python
frame[i] *= optimizedMean / statResult;
```
Where the `optimizedMean` is obtained from the electron threshold step, and the `statResult` is either the mean or the median of the half of the row that the frame pixel is in.
This also fixes a bug where we were applying the gain before dark subtraction, when it should be the other way around (dark subtraction then gain).
This also refactors the `electronCount()` methods so that there are significantly fewer template declarations to update, and the electron counting options are now placed in structs so that, from a maintainability standpoint, it is easier to add options in the future.
Fixes: #258

Add row dark algorithm to electron counting

---

python/stempy/io/sparse_array.py
tests/conftest.py
tests/test_sparse_array.py

This converts the sparse array to a fully dense array and returns it.
It is equivalent to `array[:]` if `array.allow_full_expand == True` and `array.sparse_slicing == False`.
Fixes: #265

Add `SparseArray.to_dense()`

---

python/stempy/image/__init__.py

This adds 3 functions for more detailed analysis. 
`virtual_darkfield` takes in centers and radii of circular apertures to place in diffraction space. A real space virtual darkfield image is returned where each probe position is the sum of the intensity in all apertures. See below for an example
`plot_virtual_darkfield` takes in the same arguments as `virtual_darkfield` and plots circles at each aperture position to check the output is physically meaningful.
```python
center_x = (288, 317) # col, row or X, Y from matplotlib plot
center_y = (363, 213) 
radii = (15, 15)
plot_virtual_darkfield(sp, center_x, center_y, radii)
```
`mask_real_space` takes in a boolean array of positions matching the `scan_shape` of a `SparseArray` and outputs a summed diffraction pattern. The pattern is the sum …

Add analysis functions

---

python/stempy/image/__init__.py

Code for replacing nans is missing from `stempy.image.com_sparse`. This adds that in.

com_sparse and nans

---

python/stempy/io/sparse_array.py
tests/test_sparse_array.py

Several tests were added to verify that this is working correctly. These include tests for multiple frames per scan position, slicing followed by a frame axes sum, and advanced indexing followed by a frame axes sum.
Since the mean is implemented using the sum, this addition also adds support for performing a mean along the frame axes as well.
Fixes: #277

Add implementation for summing along frame axes

---

python/io.cpp
python/stempy/io/__init__.py
stempy/reader.h

This refactors the `SectorStreamMultiPassThreadedReader` class a little bit and adds methods for reading specific frames from the data.
Reading the frames requires first reading all of the headers of the data (which can take some time, since we have to parse the data files). But once the headers have been read once, they are cached so that they do not need to be read again.
Here is some example code:
```python
import glob
import stempy.io as stio
backend = 'multi-pass'
files = glob.glob('*.data')
reader = stio.reader(files, stio.FileVersion.VERSION5, backend=backend)
blocks = reader.read_frames((5, 30), [1, 2, 3])
for block in blocks:
array = block.data  # this is the numpy array for the block
```
The `frames_slice` argument is used to slice directly into a `np.arange(num_frames)` array, …

Add method for reading frames at a scan position

---

docker/Dockerfile.scipy-notebook

Updates for new scipy-notebook image

---

python/stempy/io/sparse_array.py

This is a small PR that avoids type conversion behavior to float on integer division.
@ercius and I (mostly @ercius) figured out that this line:
```python
data = data.reshape((np.prod(scan_shape), frames_per_scan))
```
Fails with:
```python
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```
When the type of the `scan_shape` list is an unsigned int, `np.prod(scan_shape)`, and integer division results in a float64:
```python 
frames_per_scan = len(data) // np.prod(scan_shape) # (python int) // np.uint 
print(frames_per_scan.dtype)
```
This change ensures that this conversion doesn't happen.

avoid type conversion to float on h5 import

---

CMakeLists.txt
cmake/FindBigMPI.cmake
docker/Dockerfile
stempy/electron_mpi.cpp

With the new detector and multiple frames per scan position we are starting to get more events than can be sent in a regular MPI message. This adds BigMPI to increase the size of the messages we can sent to get around this restriction.

Use BigMPI to send events

---

.github/workflows/build_wheels.yml

Our current versions are using Node 12, and GitHub Actions is trying to migrate to newer versions which use Node 16. See [here](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).

Update actions to latest versions

---

python/image.cpp

Fixes #275 
Tested with python versions 3.7 - 3.10, counting works fine on Perlmutter.

acquire gil before creating numpy array

---

stempy/electron_mpi.cpp

See #292 for details on this fix. 
I think the sends/receives were mixing up the message size message and the data messages, because of MPI_ANY_SOURCE.
I tested this and it works.

Big MPI fix

---

python/stempy/contrib/__init__.py

improves on @ercius commit to enable getting scan path for new naming convention.
adds typing, and improves flow

contrib: add typing, include versions in get_scan_path

---

.github/scripts/docker/Dockerfile
.github/scripts/docker/build_and_push.sh
.github/workflows/build_wheels.yml

I believe Python 3.11 wheels were being skipped because, at the time, several dependencies did not have Python 3.11 support.
But our dependencies should have Python 3.11 support now. So let's add back in Python 3.11.
Fixes: #294

Build wheels for Python 3.11 also

---

tests/requirements.txt

This prevents us running into https://github.com/urllib3/urllib3/issues/2168 when building the wheels.

Pin to older version of urllib3

---

python/stempy/io/__init__.py
python/stempy/io/sparse_array.py
tests/test_sparse_array.py

Update `from_hdf5` to allow the user to crop the flyback column during load. For large data sets this can reduce the time needed in processing later significantly. The keyword is set to `True` to be compatible with older code. 
Need to fully test once the CI builds are available. Dont merge yet. Will update as needed.

Remove flyback

---

python/stempy/io/sparse_array.py
tests/conftest.py
tests/test_sparse_array.py

The current algorithm for removing the flyback doe snot properly account for multiple frames per probe position.
This new algorithm is designed to account for that problem.
Its not ready yet. I need to build new stempy version to test it.

Fix remove_flyback algorithm

---

python/pyreader.cpp

For the last block in a scan the number of frames may not be exactly the specified number of frames per block. So use the size of the image numbers vector.

Fix frames per block

---

.github/actions/docker_setup/action.yml
docker/Dockerfile.stempy

`mpi4py` defaults to using setuptools as backend. Changing this to `scikit-build-core` was the key here. 
Other things are useful anyway, so I keep them here - upgrading action version, and not using cache directory (smaller image sizes).

Fix docker CI builds

---

examples/sum_scans.ipynb
python/stempy/image/__init__.py
python/stempy/io/__init__.py
python/stempy/utils.py

this fixes the upgrade from np 1 -> 2 for certain functions that use `np.array(data, copy=False)`

[#334] use safe_array for np v1 or v2
