OpenChemistry/stempy

python/stempy/io/__init__.py
stempy/main.cpp
stempy/reader.cpp
stempy/reader.h

Signed-off-by: Chris Harris <chris.harris@kitware.com>

Read all of header

---

python/stempy/io/__init__.py

Signed-off-by: Chris Harris <chris.harris@kitware.com>

Make reader an iterator

---

stempy/reader.cpp

Also removed a "40," expression, since the 40 was not
being used for anything.

Remove a few unused variables

---

stempy/image.cpp

This is important with a partial image.

Ensure image values are set to zero

---

examples/create_hdf5.py
examples/electron.ipynb
python/image.cpp
python/stempy/image/__init__.py
stempy/image.cpp
stempy/image.h

Use StreamReader::iterator for calculateAverage

---

examples/benchmark_electron_counting.py

This benchmarks the file I/O, as well as the `calculate_average`
and `electron_count` methods together.

Added a benchmark script for electron counting

---

examples/create_hdf5.py

Save detector frames also in create_hdf5.py

---

examples/stem_image.ipynb

It displays the bright and dark fields with matplotlib.

Added notebook example for creating stem image

---

CMakeLists.txt
stempy/reader.cpp
stempy/sioclient.cpp

I also ran git clang-format on the changes.

Fix socket io warnings

---

docker/BUILD.md

@cryos Here are some instruction on rebuilding the shifter image if you need to make changes.

Add instruction for building shifter image

---

examples/electron_stem_image.py
examples/stem_image.py
python/image.cpp
python/stempy/image/__init__.py
python/stempy/io/__init__.py
stempy/image.cpp
stempy/image.h

This is a work in progress currently.
Fixes: #40

Add ability to calculate stem images from electron counted data

---

python/stempy/image/__init__.py

Update parameter names

---

docs/StempyH5Format.md

This reflects recent changes to the format.

Update the Stempy H5 Format doc

---

examples/stem_histogram.ipynb

This follows the same conventions as stem_image.ipynb.

Added example histogram jupyter notebook

---

python/image.cpp

This give other Python threads a look in!

Release the GIL when calling C++ functions

---

stempy/image.cpp
stempy/image.h

This should resolve #77, I have pushed the images to cori.

Fix overflow/wrap in processing sparse datasets

---

CMakeLists.txt
examples/hdf5Reader/reader_hdf5.py
python/CMakeLists.txt
python/image.cpp
python/io.cpp
python/pyreader.cpp
python/pyreader.h
python/stempy/image/__init__.py
stempy/image.cpp
stempy/reader.cpp
stempy/reader.h

add python reader to support hdf5

add python reader for hdf5

---

docker/Dockerfile

This allows the CLI examples to work.

Add click to docker image

---

stempy/electron.cpp
stempy/image.cpp

"Invoke" was placed in "cont" rather than "worklet".
Also, "CellSetStructured" does not accept a string in the
constructor anymore. It may not be needed, just remove it.

Make changes to use the master branch of vtkm

---

h5cpp/h5readwrite.cpp
h5cpp/h5readwrite.h
stempy/reader.cpp

This removes the costly introspection of the dataset.

Pass dataset dimensions to updateData(...)

---

README.md
python/stempy/image/__init__.py

Cherry-pick of #142 commits to fix issues introduced by rebase.

Rebased: sparse data processing functions and readme update

---

python/stempy/image/__init__.py

1. Fix radial_sum_sparse off by one issue for the histogram calculation. I did not test it properly before pushing. It is now tested on real data and working properly.
2. Change com_sparse so it operates on the entire counted data set rather than just one frame. This is more convenient. Tested and working on real data.

Bug fix and function improvement

---

python/io.cpp
python/stempy/io/__init__.py
stempy/reader.cpp
stempy/reader.h

This add a need file format version (5) to support contiguous sector layout.

Add support for contiguous data format

---

python/stempy/image/__init__.py

Specify dtype to fix depreciation warning

---

examples/create_images.py
examples/electron_count.py
examples/electron_count_hdf5.py
python/stempy/image/__init__.py

1) Improve the speed of the com_sparse function
2) Update the examples with code we use on the local event building PC
3) Add a com_dense function to help with analysis of raw and counted but dense frames

Improve speed, update examples, add com_dense function

---

docs/source/4dCamera_header_versions.rst

Add a description of VERSION3, VERSION4, and VERSION5 data types for raw 4D Camera files.
addresses #132

Description of raw 4D Camera data files

---

docs/source/singularity.rst

Add instructions to install the newest Singularity to avoid squashsfs error (fixes #165)
Add instructions for creating and connecting to a Jupyter Lab server.

Update singularity rst

---

python/image.cpp
stempy/image.cpp
stempy/image.h

Prevent copying numpy array electron counting data

---

python/image.cpp
python/stempy/image/__init__.py
stempy/electron.cpp
stempy/electron.h
stempy/electronthresholds.cpp
stempy/electronthresholds.h

Use template meta programming to do this without incurring any runtime penalty.
Fixes #158

Make dark reference option

---

stempy/electron.cpp

It appears some issues where introduce in the last branch. Ensure that we pass the frame type down to VTK-m

Fix maximalPointsParallel templates

---

docker/Dockerfile
docker/Dockerfile.scipy-notebook

Add ncempy to images

---

docs/source/4dCamera_header_versions.rst
docs/source/index.rst

The frame number was described as unit16 when it is actually uint32. The numpy custom dtype is correct though.

fix error in header description. 

---

docker/Dockerfile.scipy-notebook

Adjust for the latest version of the base image

---

python/stempy/image/__init__.py

These old data formats mostly do not even exist anymore. We will remove
them in the future.

Warn if electron_count() is called with old reader

---

.github/workflows/build_wheels.yml
python/CMakeLists.txt
python/stempy/image/__init__.py
python/stempy/io/compatibility.py
python/stempy/io/sparse_array.py
tests/conftest.py
tests/requirements.txt
tests/test_image.py
tests/test_sparse_array.py

This now uses the `SparseArray` class, and it takes into account the
fact that there may be multiple frames per scan position.
Fixes: #239

Update com_sparse() for new data format

---

python/stempy/io/sparse_array.py

Too many large arrays of booleans were being created and slowing down
the sparse slicing significantly for large scan sizes.
This was particularly noticeable, for instance, for a scan shape of
(1024, 1025), where we would crop off one of the scans like
```
array[:, :1024]
```
These changes reduce the number of large boolean arrays created and
seem to significantly improve the performance.
These changes will also be unnecessary and removed in V3 of the
SparseArray, which is coming soon.

Fix sparse slicing performance issues

---

python/stempy/io/sparse_array.py
tests/test_sparse_array.py

This property returns the number of frames per scan position.
Fixes: #250

Add SparseArray.num_frames_per_scan

---

docker/Dockerfile.stempy
requirements.txt

cmake is not needed at runtime ...

Remove cmake from requirements.txt

---

python/stempy/image/__init__.py

Update the docstring to the electron counting code. Its best to use a simple np.ndarray.

Docstring update
